In [2]:
#Save Model
import pandas as pd 
import numpy as np
from sklearn import linear_model

In [3]:
df=pd.read_csv('salaryData.csv')
df.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [4]:
model = linear_model.LinearRegression()
model.fit(df[['YearsExperience']],df.Salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [5]:
model.coef_

array([9449.96232146])

In [6]:
model.intercept_

25792.200198668717

In [7]:
model.predict([[2.2]])

array([46582.11730587])

In [8]:
#save model With Pickel


In [9]:
import pickle
with open('model_pickel','wb') as f:
    pickle.dump(model,f)

In [10]:
#Load Save Model

In [11]:
with open('model_pickel','rb') as f :
    m=pickle.load(f)

In [12]:
m.coef_

array([9449.96232146])

In [13]:
m.intercept_

25792.200198668717

In [14]:
m.predict([[2.2]])

array([46582.11730587])

In [15]:
# Save Model With Joblib

In [17]:
from sklearn.externals import joblib
joblib.dump(model,'model_joblib')


['model_joblib']

In [19]:
mj = joblib.load('model_joblib')
mj.coef_

array([9449.96232146])

In [20]:
mj.intercept_

25792.200198668717

In [21]:
mj.predict([[2.2]])

array([46582.11730587])